- hosts: localhost
  connection: local
  become: yes
  vars:
    domain: lab.registry.com
  tasks:
  - name: SSL dir
    file:
      path: /etc/ssl/certs/{{ domain }}
      state: directory

  - name: docker add ca
    file:
      path: /etc/docker/certs.d/{{ domain }}
      state: directory
  
  - name: create auth folder for registry
    file: 
      path: "{{ lookup('env', 'PWD') }}/registry/auth"
      state: directory
  
  - name: create auth folder for registry
    file:
      path: "{{ lookup('env', 'PWD') }}/registry/data"
      state: directory

  - name: Generate an OpenSSL priv key
    community.crypto.openssl_privatekey:
      path: /etc/ssl/certs/{{ domain }}/certificate.key

  - name: Create certificate signing request
    community.crypto.openssl_csr_pipe:
      privatekey_path: /etc/ssl/certs/{{ domain }}/certificate.key
      common_name: lab.registry.com
      organization_name: Home lab
    register: csr

  - name: Create self-signed certificate from CSR
    community.crypto.x509_certificate:
      path:  /etc/ssl/certs/{{ domain }}/certificate.pem
      csr_content: "{{ csr.csr }}"
      privatekey_path:  /etc/ssl/certs/{{ domain }}/certificate.key
      provider: selfsigned

  - name: copy ca cert
    copy:
      src: /etc/ssl/certs/{{ domain }}/certificate.pem
      dest: /etc/docker/certs.d/{{ domain }}/ca.crt
      owner: root
      group: root
      mode: "0644"
    notify: restart docker

  - name: apt-get update
    apt:
      update_cache: yes
      cache_valid_time: 3600
  
  - name: nginx install
    apt:
      name: ['nginx']
      state: latest

  - name: appache2 utis install
    apt:
      name: ['apache2-utils']
      state: latest

  - name: delete default nginx
    file:
      path: /etc/nginx/sites-enabled/default
      state: absent
    notify: restart nginx

  - name: copy site.conf
    template:
      src: site.conf.j2
      dest: /etc/nginx/sites-enabled/{{ domain }}
      owner: root
      group: root
      mode: '0644'
    notify: restart nginx

  - name: replace nginx.conf
    copy:
      src: files/nginx.conf
      dest: /etc/nginx/nginx.conf
    notify: restart nginx

  - name: create registry user string
    shell:
      cmd: htpasswd -bBc registry.password admin password 
      chdir: registry/auth

  - name: create and start registry service
    docker_compose:
      project_src: registry
    register: output

  - debug:
      var: output

  handlers:
    - name: restart nginx
      service: 
        name: nginx
        state: restarted
    - name: restart docker
      service:
        name: docker
        state: restarted

